---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - downscaler.sipher.gg
  resources:
  - downscaleschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.sipher.gg
  resources:
  - downscaleschedules/finalizers
  verbs:
  - update
- apiGroups:
  - downscaler.sipher.gg
  resources:
  - downscaleschedules/status
  verbs:
  - get
  - patch
  - update
