---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - agones.dev
  resources:
  - fleets
  - fleets/scale
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.agones.dev
  resources:
  - fleetautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.sipher.gg
  resources:
  - downscaleschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - downscaler.sipher.gg
  resources:
  - downscaleschedules/status
  verbs:
  - get
  - patch
  - update
