apiVersion: downscaler.sipher.gg/v1alpha1
kind: DownscaleSchedule
metadata:
  name: working-hours
  namespace: kube-scaledown-system
spec:
  uptime: "Mon-Sat 08:00-20:00 Asia/Ho_Chi_Minh"
  downtime: "Mon-Sat 20:00-08:00 Asia/Ho_Chi_Minh, Sun 00:00-24:00 Asia/Ho_Chi_Minh"
  downtimeReplicas: 0
  includeResources:
    - deployments
    - statefulsets
    - fleets.agones.dev
    - cronjobs
  excludeNamespaces:
    - kube-system
    - kube-downscaler
    - kube-scaledown-system
    - argocd
    - cert-manager
    - ingress-nginx
    - ingress-nginx-internal
    - monitoring
    - sipher-system
    - gatekeeper-system
    - aks-command
    - n8n
    - ather-os
    - unleash
    - nightshift
    - s2
    - pve-tool
    - trungthuy
