{{- if .Values.schedule.enabled }}
apiVersion: downscaler.sipher.gg/v1alpha1
kind: DownscaleSchedule
metadata:
  name: {{ include "kube-scaledown.fullname" . }}-schedule
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-scaledown.labels" . | nindent 4 }}
spec:
  uptime: {{ .Values.schedule.uptime | quote }}
  downtimeReplicas: {{ .Values.schedule.downtimeReplicas }}
  includeResources:
    {{- toYaml .Values.schedule.includeResources | nindent 4 }}
  excludeNamespaces:
    {{- toYaml .Values.schedule.excludeNamespaces | nindent 4 }}
{{- end }}
